const char HTML_BODY1[] =
    "<!DOCTYPE html><html lang=\"pt-br\"><head><meta charset=\"UTF-8\"><title>Estação</title>"
    "<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script><style>"
    "body{font-family:sans-serif;background:#f0f4f8;margin:0;padding:10px}h1,h2,h3{color:#1e3a5f;text-align:center}"
    ".main-flex{display:flex;flex-wrap:wrap;gap:20px;justify-content:center;align-items:flex-start}"
    ".left-col{display:flex;flex-direction:column;gap:20px;flex:1 1 340px;min-width:340px;max-width:420px}"
    ".card{background:#fff;padding:15px;margin:0;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.1);}"
    ".card.chart{flex:2 1 600px;min-width:320px;max-width:700px}"
    "h2{margin-top:0;margin-bottom:15px;color:#0056b3}.data-grid{display:grid;grid-template-columns:1fr 1fr;text-align:center;gap:10px}"
    ".data-point p{margin:0;font-size:1em;color:#555}.data-point .val{font-size:1.8em;font-weight:bold;color:#000}"
    ".cfg-tbl{width:100%;border-collapse:collapse;margin-top:10px}.cfg-tbl th,.cfg-tbl td{padding:8px;border:1px solid #ddd;text-align:center}"
    "input{font-size:1em;padding:5px;width:90px;text-align:center}button{font-size:1.1em;padding:10px 25px;border:none;border-radius:8px;background:#007bff;color:white;cursor:pointer;width:100%;margin-top:20px}"
    ".chart-container{position:relative;height:200px;width:98%;margin:auto}"
    "@media (max-width:900px){.main-flex{flex-direction:column;gap:10px}.left-col{max-width:100%}.card.chart{max-width:100%}}"
    "</style></head>"
    "<body><h1>Estação Meteorológica</h1>"
    "<div class=\"main-flex\">"
    "<div class=\"left-col\">"
    "<div class=\"card\"><h2>Condições Atuais</h2><div class=\"data-grid\">"
    "<div class=\"data-point\"><p>Temp. AHT</p><span class=\"val\" id=\"t_aht\">?.?</span>&deg;C</div>"
    "<div class=\"data-point\"><p>Umidade</p><span class=\"val\" id=\"h\">?.?</span>%</div>"
    "<div class=\"data-point\"><p>Temp. BMP</p><span class=\"val\" id=\"t_bmp\">?.?</span>&deg;C</div>"
    "<div class=\"data-point\"><p>Altitude</p><span class=\"val\" id=\"alt\">?</span>m</div>"
    "<div class=\"data-point\" style=\"grid-column:1/-1\"><p>Pressão</p><span class=\"val\" id=\"p\">?.?</span> hPa</div>"
    "</div></div>"
    "<div class=\"card\"><h2>Configurações</h2><form onsubmit=\"s(event)\">"
    "<h3>Limites de Alerta</h3><table class=\"cfg-tbl\">"
    "<tr><th>Parâmetro</th><th>Mínimo</th><th>Máximo</th></tr>"
    "<tr><td>Temperatura (°C)</td><td><input type=\"number\" id=\"i_t_min\"></td><td><input type=\"number\" id=\"i_t_max\"></td></tr>"
    "<tr><td>Umidade (%)</td><td><input type=\"number\" id=\"i_h_min\"></td><td><input type=\"number\" id=\"i_h_max\"></td></tr>"
    "<tr><td>Pressão (hPa)</td><td><input type=\"number\" id=\"i_p_min\"></td><td><input type=\"number\" id=\"i_p_max\"></td></tr>"
    "</table><h3 style=\"margin-top:20px\">Calibração</h3><table class=\"cfg-tbl\">"
    "<tr><th>Parâmetro</th><th>Offset</th></tr>"
    "<tr><td>Temperatura</td><td><input type=\"number\" id=\"i_t_off\"></td></tr>"
    "<tr><td>Umidade</td><td><input type=\"number\" id=\"i_h_off\"></td></tr>"
    "<tr><td>Pressão</td><td><input type=\"number\" id=\"i_p_off\"></td></tr>"
    "</table><button type=\"submit\">Salvar</button></form></div>"
    "</div>"
    "<div class=\"card chart\"><h2>Históricos</h2>"
    "<h3>Temperatura AHT</h3><div class=\"chart-container\"><canvas id=\"g_t\"></canvas></div>"
    "<h3>Umidade</h3><div class=\"chart-container\"><canvas id=\"g_h\"></canvas></div>"
    "<h3>Pressão</h3><div class=\"chart-container\"><canvas id=\"g_p\"></canvas></div>"
    "</div>"
    "</div>"
    "<script>"
    "let g={};function c(i,l,o){const t=document.getElementById(i).getContext('2d');return new Chart(t,{type:'line',data:{datasets:[{label:l,data:[],borderColor:o}]},options:{responsive:!0,maintainAspectRatio:!1}})}"
    "function p(d){if(d.config){const l=d.config.limites;const o=d.config.offsets;document.getElementById('i_t_min').value=l.temp_min;document.getElementById('i_t_max').value=l.temp_max;document.getElementById('i_h_min').value=l.umid_min;document.getElementById('i_h_max').value=l.umid_max;document.getElementById('i_p_min').value=l.pres_min;document.getElementById('i_p_max').value=l.pres_max;document.getElementById('i_t_off').value=o.temp_offset;document.getElementById('i_h_off').value=o.umid_offset;document.getElementById('i_p_off').value=o.pres_offset;}}"
    "function u(d){document.getElementById('t_aht').innerText=d.temperatura_aht.toFixed(1);document.getElementById('h').innerText=d.umidade.toFixed(1);document.getElementById('t_bmp').innerText=d.temperatura_bmp.toFixed(1);document.getElementById('p').innerText=d.pressao.toFixed(1);document.getElementById('alt').innerText=d.altitude.toFixed(0);if(d.historico){const h=d.historico;const l=Array.from({length:h.temperatura.length},(_,i)=>i+1);g.t.data.labels=l;g.t.data.datasets[0].data=h.temperatura;g.t.update('none');g.h.data.labels=l;g.h.data.datasets[0].data=h.umidade;g.h.update('none');g.p.data.labels=l;g.p.data.datasets[0].data=h.pressao;g.p.update('none')}}"
    "function f(){fetch('/data').then(r=>r.json()).then(d=>u(d))}"
    "function i(){fetch('/data').then(r=>r.json()).then(d=>{p(d);u(d)})}"
    "function s(e){e.preventDefault();const d={limites:{temp_min:Number(document.getElementById('i_t_min').value),temp_max:Number(document.getElementById('i_t_max').value),umid_min:Number(document.getElementById('i_h_min').value),umid_max:Number(document.getElementById('i_h_max').value),pres_min:Number(document.getElementById('i_p_min').value),pres_max:Number(document.getElementById('i_p_max').value)},offsets:{temp_offset:Number(document.getElementById('i_t_off').value),umid_offset:Number(document.getElementById('i_h_off').value),pres_offset:Number(document.getElementById('i_p_off').value)}};fetch('/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}).then(async r=>{const msg=await r.text();alert(r.ok?'Salvo':'Erro: '+msg);});}"
    "document.addEventListener('DOMContentLoaded',()=>{g.t=c('g_t','Temp','#FF6384');g.h=c('g_h','Umid','#36A2EB');g.p=c('g_p','Press','#FFCE56');i();setInterval(f,5000)})"
    "</script></body></html>";
const char HTML_BODY2[] =
    "<!DOCTYPE html><html lang=\"pt-br\"><head><meta charset=\"UTF-8\"><title>Estação</title>"
    "<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script><style>"
    "body{font-family:sans-serif;background:#f0f4f8;margin:0;padding:10px}h1,h2,h3{color:#1e3a5f;text-align:center}"
    ".mf{display:flex;flex-wrap:wrap;gap:20px;justify-content:center;align-items:flex-start}"
    ".lc{display:flex;flex-direction:column;gap:20px;flex:1 1 340px;min-width:340px;max-width:420px}"
    ".cd{background:#fff;padding:15px;margin:0;border:1px solid #eee}"
    ".cd.ch{flex:2 1 600px;min-width:320px;max-width:700px}"
    "h2{margin-top:0;margin-bottom:15px;color:#0056b3}.dg{display:grid;grid-template-columns:1fr 1fr;text-align:center;gap:10px}"
    ".dp p{margin:0;font-size:1em;color:#555}.dp .v{font-size:1.8em;font-weight:bold;color:#000}"
    ".ct{width:100%;border-collapse:collapse;margin-top:10px}.ct th,.ct td{padding:8px;border:1px solid #ddd;text-align:center}"
    "input{font-size:1em;padding:5px;width:90px;text-align:center}button{font-size:1.1em;padding:10px 25px;border:none;background:#007bff;color:white;cursor:pointer;width:100%;margin-top:20px}"
    ".cc{position:relative;height:200px;width:98%;margin:auto}"
    "@media (max-width:900px){.mf{flex-direction:column;gap:10px}.lc{max-width:100%}.cd.ch{max-width:100%}}"
    "</style></head>"
    "<body><h1>Estação Meteorológica</h1>"
    "<div class=\"mf\">"
    "<div class=\"lc\">"
    "<div class=\"cd\"><h2>Atuais</h2><div class=\"dg\">"
    "<div class=\"dp\"><p>Temp. AHT</p><span class=\"v\" id=\"t_aht\">?.?</span>&deg;C</div>"
    "<div class=\"dp\"><p>Umidade</p><span class=\"v\" id=\"h\">?.?</span>%</div>"
    "<div class=\"dp\"><p>Temp. BMP</p><span class=\"v\" id=\"t_bmp\">?.?</span>&deg;C</div>"
    "<div class=\"dp\"><p>Altitude</p><span class=\"v\" id=\"alt\">?</span>m</div>"
    "<div class=\"dp\" style=\"grid-column:1/-1\"><p>Pressão</p><span class=\"v\" id=\"p\">?.?</span> hPa</div>"
    "</div></div>"
    "<div class=\"cd\"><h2>Ajustes</h2><form onsubmit=\"s(event)\">"
    "<h3>Alertas</h3><table class=\"ct\">"
    "<tr><th>Parâm.</th><th>Mín.</th><th>Máx.</th></tr>"
    "<tr><td>Temp (°C)</td><td><input type=\"number\" id=\"i_t_min\"></td><td><input type=\"number\" id=\"i_t_max\"></td></tr>"
    "<tr><td>Umid (%)</td><td><input type=\"number\" id=\"i_h_min\"></td><td><input type=\"number\" id=\"i_h_max\"></td></tr>"
    "<tr><td>Press (hPa)</td><td><input type=\"number\" id=\"i_p_min\"></td><td><input type=\"number\" id=\"i_p_max\"></td></tr>"
    "</table><h3 style=\"margin-top:20px\">Calibrar</h3><table class=\"ct\">"
    "<tr><th>Parâm.</th><th>Offset</th></tr>"
    "<tr><td>Temp.</td><td><input type=\"number\" id=\"i_t_off\"></td></tr>"
    "<tr><td>Umid.</td><td><input type=\"number\" id=\"i_h_off\"></td></tr>"
    "<tr><td>Press.</td><td><input type=\"number\" id=\"i_p_off\"></td></tr>"
    "</table><button type=\"submit\">Salvar</button></form></div>"
    "</div>"
    "<div class=\"cd ch\"><h2>Gráficos</h2>"
    "<h3>Temperatura AHT</h3><div class=\"cc\"><canvas id=\"g_t\"></canvas></div>"
    "<h3>Umidade</h3><div class=\"cc\"><canvas id=\"g_h\"></canvas></div>"
    "<h3>Pressão</h3><div class=\"cc\"><canvas id=\"g_p\"></canvas></div>"
    "</div>"
    "</div>"
    "<script>"
    // --- JAVASCRIPT CORRIGIDO ---
    "const E=(id)=>document.getElementById(id);let g={};function c(i,l,o){const t=E(i).getContext('2d');return new Chart(t,{type:'line',data:{datasets:[{label:l,data:[],borderColor:o}]},options:{responsive:!0,maintainAspectRatio:!1}})}"
    "function p(d){if(d.config){const l=d.config.limites;const o=d.config.offsets;E('i_t_min').value=l.temp_min;E('i_t_max').value=l.temp_max;E('i_h_min').value=l.umid_min;E('i_h_max').value=l.umid_max;E('i_p_min').value=l.pres_min;E('i_p_max').value=l.pres_max;E('i_t_off').value=o.temp_offset;E('i_h_off').value=o.umid_offset;E('i_p_off').value=o.pres_offset;}}"
    "function u(d){E('t_aht').innerText=d.temperatura_aht.toFixed(1);E('h').innerText=d.umidade.toFixed(1);E('t_bmp').innerText=d.temperatura_bmp.toFixed(1);E('p').innerText=d.pressao.toFixed(1);E('alt').innerText=d.altitude.toFixed(0);if(d.config){const l=d.config.limites;E('t_aht').style.color=d.temperatura_aht<l.temp_min||d.temperatura_aht>l.temp_max?'red':'#000';E('t_bmp').style.color=d.temperatura_bmp<l.temp_min||d.temperatura_bmp>l.temp_max?'red':'#000';E('h').style.color=d.umidade<l.umid_min||d.umidade>l.umid_max?'red':'#000';E('p').style.color=d.pressao<l.pres_min||d.pressao>l.pres_max?'red':'#000';}if(d.historico){const h=d.historico;const l=Array.from({length:h.temperatura.length},(_,i)=>i+1);g.t.data.labels=l;g.t.data.datasets[0].data=h.temperatura;g.t.update('none');g.h.data.labels=l;g.h.data.datasets[0].data=h.umidade;g.h.update('none');g.p.data.labels=l;g.p.data.datasets[0].data=h.pressao;g.p.update('none')}}"
    "function f(){fetch('/data').then(r=>r.json()).then(d=>u(d))}"
    "function i(){fetch('/data').then(r=>r.json()).then(d=>{p(d);u(d)})}"
    "function s(e){e.preventDefault();const d={limites:{temp_min:Number(E('i_t_min').value),temp_max:Number(E('i_t_max').value),umid_min:Number(E('i_h_min').value),umid_max:Number(E('i_h_max').value),pres_min:Number(E('i_p_min').value),pres_max:Number(E('i_p_max').value)},offsets:{temp_offset:Number(E('i_t_off').value),umid_offset:Number(E('i_h_off').value),pres_offset:Number(E('i_p_off').value)}};fetch('/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}).then(async r=>{const msg=await r.text();alert(r.ok?'Salvo':'Erro: '+msg);});}"
    "document.addEventListener('DOMContentLoaded',()=>{g.t=c('g_t','Temp','#FF6384');g.h=c('g_h','Umid','#36A2EB');g.p=c('g_p','Press','#FFCE56');i();setInterval(f,5000)})"
    "</script></body></html>";